name: xtream-data

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir çalışır

jobs:
  GenerateXtreamData:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4.2.2

      - name: Python 3.11 Yükle
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11

      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -U requests cloudscraper

      - name: Xtream Codes Verilerini Oluştur
        run: python generator.py

      - name: Değişiklik Kontrolü
        id: degisiklik_kontrol
        run: |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT

      - name: Değişiklikleri Commit Et
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🚀 Xtream Codes verileri güncellendi" -m "🕒 Otomatik işlem - $GITHUB_SHA"
          git push
